export const DATA = [
  {
    id: 1,
    name: "Function 1",
    executionOrder: 1,
    equation: "x ^ 2",
    nextFunction: 2,
    displayOrder: 1,
  },
  {
    id: 2,
    name: "Function 2 ",
    executionOrder: 2,
    equation: "2 * x + 4",
    nextFunction: 4,
    displayOrder: 2,
  },
  {
    id: 3,
    name: "Function 3",
    executionOrder: 5,
    equation: "x ^ 2 + 20",
    nextFunction: "",
    displayOrder: 3,
  },
  {
    id: 4,
    name: "Function 4",
    executionOrder: 3,
    equation: "x - 2",
    nextFunction: 5,
    displayOrder: 4,
  },
  {
    id: 5,
    name: "Function 5",
    executionOrder: 4,
    equation: "x / 2",
    nextFunction: 3,
    displayOrder: 5,
  },
];
